version: '3.8'

services:
  app:
    image: ${APP_IMAGE:-ghcr.io/phcteixeira/crm-app:latest}
    container_name: crm-app
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - EVOLUTION_API_URL=${EVOLUTION_API_URL}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - DOMAIN=${DOMAIN}
      - PORT=${PORT:-3005}
    networks:
      - maracainet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crm-app.rule=Host(`crm.ckmedia.com.br`)"
      - "traefik.http.routers.crm-app.entrypoints=websecure"
      - "traefik.http.routers.crm-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.crm-app.loadbalancer.server.port=${PORT:-3005}"

networks:
  maracainet:
    external: true
